"""State schema for the agent graph."""

from enum import Enum
from typing import TypedDict


class NodeStatus(Enum):
    """Status returned by each node."""

    CONTINUE = "continue"
    DONE = "done"
    NEEDS_INFO = "needs_info"
    FAILED = "failed"


class AgentState(TypedDict):
    """Shared state passed between all nodes.

    Attributes:
        input: The original user query or request
        plan: List of steps generated by the Planner
        current_step: Which step we're currently working on
        research_findings: Summarized findings from the Researcher
        builder_output: Code changes or execution results from the Builder
        messages: Conversation history / log
        status: Current overall status
        next_node: Which node to route to next
        feedback: Optional feedback from user or validation (for replanning)
        iteration: How many times we've looped through the graph
        max_iterations: Maximum iterations before stopping (prevents infinite loops)
    """

    input: str
    plan: list[str]
    current_step: int
    research_findings: str | None
    builder_output: str | None
    messages: list[str]
    status: str
    next_node: str
    feedback: str | None
    iteration: int
    max_iterations: int
